tracing_override: null
data_root_path: /var/lib/holochain
keystore:
  type: lair_server_in_proc
  lair_root: /var/lib/holochain/keystore
admin_interfaces:
  - driver:
      type: websocket
      port: 8888
      allowed_origins: "*"
